/**
 * Handover codes: the 6-digit secret attached to every order, known only by
 * the customer who placed it. The pharmacist (pickup handover) and the courier
 * (delivery handover) must collect it from the customer to close the order.
 *
 * Codes are stored hashed (scrypt, same scheme as account PINs) so no
 * pharmacist/courier-facing endpoint can ever read them — they can only be
 * verified, or regenerated by the customer.
 */
import { randomInt } from 'crypto';
import { hashPin, verifyPin } from '../auth.js';

export function newHandoverCode(): string {
  return String(randomInt(0, 1_000_000)).padStart(6, '0');
}

export function hashHandoverCode(code: string): string {
  return hashPin(code);
}

/** Constant-time verification against the stored hash. */
export function handoverCodeMatches(code: string, hash: string | null): boolean {
  return !!hash && /^\d{6}$/.test(code) && verifyPin(code, hash);
}
